allowBuilds:
  esbuild: true
  lefthook: true
publicHoistPattern:
  - eslint
  - prettier
  - vitest
  - lefthook
minimumReleaseAgeExclude:
  - '@siberiacancode/reactuse'
  - '@siberiacancode/uikit'
  - '@siberiacancode/playwright@1.0.0'
