/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as LoginRouteRouteImport } from './../../routes/login/route'
import { Route as layoutRouteRouteImport } from './../../routes/(layout)/route'
import { Route as LoginIndexRouteImport } from './../../routes/login/index'
import { Route as layoutIndexRouteImport } from './../../routes/(layout)/index'
import { Route as LoginCodeRouteImport } from './../../routes/login/code'
import { Route as layoutAuthenticatedRouteRouteImport } from './../../routes/(layout)/_authenticated/route'
import { Route as layoutGamesSlugRouteImport } from './../../routes/(layout)/games/$slug'
import { Route as layoutAuthenticatedProfileIndexRouteImport } from './../../routes/(layout)/_authenticated/profile/index'
import { Route as layoutAuthenticatedHistoryIndexRouteImport } from './../../routes/(layout)/_authenticated/history/index'
import { Route as layoutAuthenticatedHistoryOrderIdRouteImport } from './../../routes/(layout)/_authenticated/history/$orderId'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutRouteRoute = layoutRouteRouteImport.update({
  id: '/(layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const layoutIndexRoute = layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const LoginCodeRoute = LoginCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => LoginRouteRoute,
} as any)
const layoutAuthenticatedRouteRoute =
  layoutAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutGamesSlugRoute = layoutGamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutAuthenticatedProfileIndexRoute =
  layoutAuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => layoutAuthenticatedRouteRoute,
  } as any)
const layoutAuthenticatedHistoryIndexRoute =
  layoutAuthenticatedHistoryIndexRouteImport.update({
    id: '/history/',
    path: '/history/',
    getParentRoute: () => layoutAuthenticatedRouteRoute,
  } as any)
const layoutAuthenticatedHistoryOrderIdRoute =
  layoutAuthenticatedHistoryOrderIdRouteImport.update({
    id: '/history/$orderId',
    path: '/history/$orderId',
    getParentRoute: () => layoutAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRouteWithChildren
  '/login/code': typeof LoginCodeRoute
  '/': typeof layoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/games/$slug': typeof layoutGamesSlugRoute
  '/history/$orderId': typeof layoutAuthenticatedHistoryOrderIdRoute
  '/history/': typeof layoutAuthenticatedHistoryIndexRoute
  '/profile/': typeof layoutAuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/login/code': typeof LoginCodeRoute
  '/': typeof layoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/games/$slug': typeof layoutGamesSlugRoute
  '/history/$orderId': typeof layoutAuthenticatedHistoryOrderIdRoute
  '/history': typeof layoutAuthenticatedHistoryIndexRoute
  '/profile': typeof layoutAuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(layout)': typeof layoutRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/(layout)/_authenticated': typeof layoutAuthenticatedRouteRouteWithChildren
  '/login/code': typeof LoginCodeRoute
  '/(layout)/': typeof layoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/(layout)/games/$slug': typeof layoutGamesSlugRoute
  '/(layout)/_authenticated/history/$orderId': typeof layoutAuthenticatedHistoryOrderIdRoute
  '/(layout)/_authenticated/history/': typeof layoutAuthenticatedHistoryIndexRoute
  '/(layout)/_authenticated/profile/': typeof layoutAuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/login/code'
    | '/'
    | '/login/'
    | '/games/$slug'
    | '/history/$orderId'
    | '/history/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login/code'
    | '/'
    | '/login'
    | '/games/$slug'
    | '/history/$orderId'
    | '/history'
    | '/profile'
  id:
    | '__root__'
    | '/(layout)'
    | '/login'
    | '/(layout)/_authenticated'
    | '/login/code'
    | '/(layout)/'
    | '/login/'
    | '/(layout)/games/$slug'
    | '/(layout)/_authenticated/history/$orderId'
    | '/(layout)/_authenticated/history/'
    | '/(layout)/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  layoutRouteRoute: typeof layoutRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)': {
      id: '/(layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/(layout)/': {
      id: '/(layout)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof layoutIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/login/code': {
      id: '/login/code'
      path: '/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginCodeRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/(layout)/_authenticated': {
      id: '/(layout)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutAuthenticatedRouteRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/games/$slug': {
      id: '/(layout)/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof layoutGamesSlugRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/_authenticated/profile/': {
      id: '/(layout)/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof layoutAuthenticatedProfileIndexRouteImport
      parentRoute: typeof layoutAuthenticatedRouteRoute
    }
    '/(layout)/_authenticated/history/': {
      id: '/(layout)/_authenticated/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof layoutAuthenticatedHistoryIndexRouteImport
      parentRoute: typeof layoutAuthenticatedRouteRoute
    }
    '/(layout)/_authenticated/history/$orderId': {
      id: '/(layout)/_authenticated/history/$orderId'
      path: '/history/$orderId'
      fullPath: '/history/$orderId'
      preLoaderRoute: typeof layoutAuthenticatedHistoryOrderIdRouteImport
      parentRoute: typeof layoutAuthenticatedRouteRoute
    }
  }
}

interface layoutAuthenticatedRouteRouteChildren {
  layoutAuthenticatedHistoryOrderIdRoute: typeof layoutAuthenticatedHistoryOrderIdRoute
  layoutAuthenticatedHistoryIndexRoute: typeof layoutAuthenticatedHistoryIndexRoute
  layoutAuthenticatedProfileIndexRoute: typeof layoutAuthenticatedProfileIndexRoute
}

const layoutAuthenticatedRouteRouteChildren: layoutAuthenticatedRouteRouteChildren =
  {
    layoutAuthenticatedHistoryOrderIdRoute:
      layoutAuthenticatedHistoryOrderIdRoute,
    layoutAuthenticatedHistoryIndexRoute: layoutAuthenticatedHistoryIndexRoute,
    layoutAuthenticatedProfileIndexRoute: layoutAuthenticatedProfileIndexRoute,
  }

const layoutAuthenticatedRouteRouteWithChildren =
  layoutAuthenticatedRouteRoute._addFileChildren(
    layoutAuthenticatedRouteRouteChildren,
  )

interface layoutRouteRouteChildren {
  layoutAuthenticatedRouteRoute: typeof layoutAuthenticatedRouteRouteWithChildren
  layoutIndexRoute: typeof layoutIndexRoute
  layoutGamesSlugRoute: typeof layoutGamesSlugRoute
}

const layoutRouteRouteChildren: layoutRouteRouteChildren = {
  layoutAuthenticatedRouteRoute: layoutAuthenticatedRouteRouteWithChildren,
  layoutIndexRoute: layoutIndexRoute,
  layoutGamesSlugRoute: layoutGamesSlugRoute,
}

const layoutRouteRouteWithChildren = layoutRouteRoute._addFileChildren(
  layoutRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginCodeRoute: typeof LoginCodeRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginCodeRoute: LoginCodeRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  layoutRouteRoute: layoutRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
