/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../routes/__root'
import { Route as LoginRouteRouteImport } from './../../routes/login/route'
import { Route as layoutRouteRouteImport } from './../../routes/(layout)/route'
import { Route as LoginIndexRouteImport } from './../../routes/login/index'
import { Route as layoutIndexRouteImport } from './../../routes/(layout)/index'
import { Route as LoginCodeRouteImport } from './../../routes/login/code'
import { Route as layoutAuthenticatedRouteRouteImport } from './../../routes/(layout)/_authenticated/route'
import { Route as layoutGamesSlugRouteImport } from './../../routes/(layout)/games/$slug'
import { Route as layoutAuthenticatedProfileRouteImport } from './../../routes/(layout)/_authenticated/profile'
import { Route as layoutAuthenticatedHistoryRouteImport } from './../../routes/(layout)/_authenticated/history'

const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const layoutRouteRoute = layoutRouteRouteImport.update({
  id: '/(layout)',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRouteRoute,
} as any)
const layoutIndexRoute = layoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => layoutRouteRoute,
} as any)
const LoginCodeRoute = LoginCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => LoginRouteRoute,
} as any)
const layoutAuthenticatedRouteRoute =
  layoutAuthenticatedRouteRouteImport.update({
    id: '/_authenticated',
    getParentRoute: () => layoutRouteRoute,
  } as any)
const layoutGamesSlugRoute = layoutGamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => layoutRouteRoute,
} as any)
const layoutAuthenticatedProfileRoute =
  layoutAuthenticatedProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => layoutAuthenticatedRouteRoute,
  } as any)
const layoutAuthenticatedHistoryRoute =
  layoutAuthenticatedHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => layoutAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRouteRouteWithChildren
  '/login/code': typeof LoginCodeRoute
  '/': typeof layoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/history': typeof layoutAuthenticatedHistoryRoute
  '/profile': typeof layoutAuthenticatedProfileRoute
  '/games/$slug': typeof layoutGamesSlugRoute
}
export interface FileRoutesByTo {
  '/login/code': typeof LoginCodeRoute
  '/': typeof layoutIndexRoute
  '/login': typeof LoginIndexRoute
  '/history': typeof layoutAuthenticatedHistoryRoute
  '/profile': typeof layoutAuthenticatedProfileRoute
  '/games/$slug': typeof layoutGamesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(layout)': typeof layoutRouteRouteWithChildren
  '/login': typeof LoginRouteRouteWithChildren
  '/(layout)/_authenticated': typeof layoutAuthenticatedRouteRouteWithChildren
  '/login/code': typeof LoginCodeRoute
  '/(layout)/': typeof layoutIndexRoute
  '/login/': typeof LoginIndexRoute
  '/(layout)/_authenticated/history': typeof layoutAuthenticatedHistoryRoute
  '/(layout)/_authenticated/profile': typeof layoutAuthenticatedProfileRoute
  '/(layout)/games/$slug': typeof layoutGamesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/login/code'
    | '/'
    | '/login/'
    | '/history'
    | '/profile'
    | '/games/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/login/code' | '/' | '/login' | '/history' | '/profile' | '/games/$slug'
  id:
    | '__root__'
    | '/(layout)'
    | '/login'
    | '/(layout)/_authenticated'
    | '/login/code'
    | '/(layout)/'
    | '/login/'
    | '/(layout)/_authenticated/history'
    | '/(layout)/_authenticated/profile'
    | '/(layout)/games/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  layoutRouteRoute: typeof layoutRouteRouteWithChildren
  LoginRouteRoute: typeof LoginRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(layout)': {
      id: '/(layout)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/(layout)/': {
      id: '/(layout)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof layoutIndexRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/login/code': {
      id: '/login/code'
      path: '/code'
      fullPath: '/login/code'
      preLoaderRoute: typeof LoginCodeRouteImport
      parentRoute: typeof LoginRouteRoute
    }
    '/(layout)/_authenticated': {
      id: '/(layout)/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof layoutAuthenticatedRouteRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/games/$slug': {
      id: '/(layout)/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof layoutGamesSlugRouteImport
      parentRoute: typeof layoutRouteRoute
    }
    '/(layout)/_authenticated/profile': {
      id: '/(layout)/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof layoutAuthenticatedProfileRouteImport
      parentRoute: typeof layoutAuthenticatedRouteRoute
    }
    '/(layout)/_authenticated/history': {
      id: '/(layout)/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof layoutAuthenticatedHistoryRouteImport
      parentRoute: typeof layoutAuthenticatedRouteRoute
    }
  }
}

interface layoutAuthenticatedRouteRouteChildren {
  layoutAuthenticatedHistoryRoute: typeof layoutAuthenticatedHistoryRoute
  layoutAuthenticatedProfileRoute: typeof layoutAuthenticatedProfileRoute
}

const layoutAuthenticatedRouteRouteChildren: layoutAuthenticatedRouteRouteChildren =
  {
    layoutAuthenticatedHistoryRoute: layoutAuthenticatedHistoryRoute,
    layoutAuthenticatedProfileRoute: layoutAuthenticatedProfileRoute,
  }

const layoutAuthenticatedRouteRouteWithChildren =
  layoutAuthenticatedRouteRoute._addFileChildren(
    layoutAuthenticatedRouteRouteChildren,
  )

interface layoutRouteRouteChildren {
  layoutAuthenticatedRouteRoute: typeof layoutAuthenticatedRouteRouteWithChildren
  layoutIndexRoute: typeof layoutIndexRoute
  layoutGamesSlugRoute: typeof layoutGamesSlugRoute
}

const layoutRouteRouteChildren: layoutRouteRouteChildren = {
  layoutAuthenticatedRouteRoute: layoutAuthenticatedRouteRouteWithChildren,
  layoutIndexRoute: layoutIndexRoute,
  layoutGamesSlugRoute: layoutGamesSlugRoute,
}

const layoutRouteRouteWithChildren = layoutRouteRoute._addFileChildren(
  layoutRouteRouteChildren,
)

interface LoginRouteRouteChildren {
  LoginCodeRoute: typeof LoginCodeRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteRouteChildren: LoginRouteRouteChildren = {
  LoginCodeRoute: LoginCodeRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteRouteWithChildren = LoginRouteRoute._addFileChildren(
  LoginRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  layoutRouteRoute: layoutRouteRouteWithChildren,
  LoginRouteRoute: LoginRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
