export const CASE_IDS = {
  BANNER_DESIGN: 'store-banner-design',
  CATALOG_DATA: 'store-catalog-data',
  CATALOG_DESIGN: 'store-catalog-design',
  CATALOG_EMPTY_DESIGN: 'store-catalog-empty-design',
  CATALOG_GAME_DETAILS: 'store-catalog-game-details',
  CATALOG_LOADING: 'store-catalog-loading',
  CATALOG_MORE: 'store-catalog-more',
  CATALOG_MORE_LAST_PAGE: 'store-catalog-more-last-page',
  CATALOG_MORE_SINGLE_PAGE: 'store-catalog-more-single-page',
  CATALOG_PRICE_DISCOUNT: 'store-catalog-price-discount',
  CATALOG_PRICE_FREE: 'store-catalog-price-free',
  CATALOG_PRICE_FULL_DISCOUNT: 'store-catalog-price-full-discount',
  CATALOG_PRICE_NO_DISCOUNT: 'store-catalog-price-no-discount',
  PAGE_DESIGN: 'store-page-design',
  VIEWS_ALL: 'store-views-all',
  VIEWS_DEFAULT: 'store-views-default',
  VIEWS_DESIGN: 'store-views-design',
  VIEWS_FILTERS_PRESERVED: 'store-views-filters-preserved',
  VIEWS_INVALID: 'store-views-invalid',
  VIEWS_NEW: 'store-views-new',
  VIEWS_POPULAR: 'store-views-popular',
  VIEWS_SCROLL: 'store-views-scroll',
  VIEWS_URL: 'store-views-url'
} as const;
